### ISSUE TITLE
TypeError: app.use() requires middleware functions

### ISSUE THREAD

**Issue by matthijsln** [opengeogroep/safetymapsDBK#15]
```
matthijsln@b3p-matthijs:~/dev/dbk/safetymapsDBK-master$ npm test

> opendispatcher@3.1.0 test /home/matthijsln/dev/dbk/safetymapsDBK-master
> mocha test --timeout 30000 --reporter dot --bail --check-leaks test/


/home/matthijsln/dev/dbk/safetymapsDBK-master/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
          ^
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/home/matthijsln/dev/dbk/safetymapsDBK-master/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/home/matthijsln/dev/dbk/safetymapsDBK-master/server.js:113:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/matthijsln/dev/dbk/safetymapsDBK-master/test/testBag.js:22:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/matthijsln/dev/dbk/safetymapsDBK-master/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/matthijsln/dev/dbk/safetymapsDBK-master/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/home/matthijsln/dev/dbk/safetymapsDBK-master/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/home/matthijsln/dev/dbk/safetymapsDBK-master/node_modules/mocha/bin/_mocha:401:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by matthijsln** [comment]
https://github.com/opengeogroep/safetymapsDBK/blob/master/server.js#L113

**Comment by matthijsln** [comment]
i18next 1.x is not compatible with Express 4

**Comment by matthijsln** [comment]
Because i18next is specified as * in package.json version 2.0.10 was used, reverting to 1.10.6
