### ISSUE TITLE
Test failure OpenDispatcher Routes GET /api/object/1.json

### ISSUE THREAD

**Issue by matthijsln** [opengeogroep/safetymapsDBK#16]
```
      AssertionError: Should return A DBKObject
      + expected - actual

      -true
      +false
      
      at Test.<anonymous> (test/testRoutes.js:76:18)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at net.js:1273:10
```

**Comment by milovanderlinden** [comment]
This issue was moved to dogodigi/opendispatcher#441
