### ISSUE TITLE
nodeless.js script is broken

### ISSUE THREAD

**Issue by matthijsln** [opengeogroep/safetymapsDBK#19]
```
Copy i18next...

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './node_modules/i18next/lib/dep/i18next.js'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.<anonymous> (/home/matthijsln/dev/dbk/safetymapsDBK-master/nodeless.js:79:53)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by matthijsln** [comment]
i18next not suitable for static use
